/*
 * generated by Xtext
 */
package org.xtext.example.boxes.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.boxes.services.BoxesDslGrammarAccess;

public class BoxesDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BoxesDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.boxes.parser.antlr.internal.InternalBoxesDslParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.boxes.parser.antlr.internal.InternalBoxesDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Box";
	}
	
	public BoxesDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BoxesDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
