/*
 * generated by Xtext
 */
package org.xtext.example.boxes.ui.contentassist

import org.xtext.example.boxes.ui.contentassist.AbstractBoxesDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class BoxesDslProposalProvider extends AbstractBoxesDslProposalProvider {
}
