/*
 * generated by Xtext
 */
package org.xtext.example.boxes.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BoxesDslUiModule extends org.xtext.example.boxes.ui.AbstractBoxesDslUiModule {
	public BoxesDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
