/*
 * generated by Xtext
 */
package org.xtext.example.boxes;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BoxesDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.example.boxes.ui.internal.BoxesDslActivator.getInstance().getInjector("org.xtext.example.boxes.BoxesDsl");
	}
	
}
