/*
 * generated by Xtext
 */
package org.xtext.example.boxes;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BoxesDslStandaloneSetup extends BoxesDslStandaloneSetupGenerated{

	public static void doSetup() {
		new BoxesDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

