/*
 * generated by Xtext
 */
package org.xtext.example.boxes;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BoxesDslRuntimeModule extends org.xtext.example.boxes.AbstractBoxesDslRuntimeModule {

}
