/*
 * generated by Xtext
 */
package org.xtext.example.boxes.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.boxes.ui.internal.BoxesDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BoxesDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BoxesDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BoxesDslActivator.getInstance().getInjector(BoxesDslActivator.ORG_XTEXT_EXAMPLE_BOXES_BOXESDSL);
	}
	
}
